apiVersion: v1
kind: Pod
metadata:
  name: gitops-pod-dummy
  namespace: gitops-tests
spec:
  containers:
  - name: pod-dummy
    image: registry.access.redhat.com/ubi9:9.8-1788939089
    command: ["/bin/sh", "-c", "sleep 3600"]
